Sort bed file after converted from bam
Error from "bedtools intersect" as follow:
ERROR: chromomsome sort ordering for file ./results/MMhur/example_MMhur_R1_trimmed_mappedToGenome_withDupes.bed is inconsistent with other files. Record was:
chr1	3277950	3278012	172503-1	255	-